name: Deploy project

on:
  pull_request:
    types: [closed]

jobs:
  merge-jobs:
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-slim
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Installing sfdx git delta"
        run: |
          echo y | sf plugins:install sfdx-git-delta
          sf plugins

      - name: "Populate auth file with SFDX_URL secret of pipelinesorg org"
        run: |
          echo ${{ secrets.SFDX_AUTH_URL}} > ./authFile.txt

      # Authenticate to org using the URL stored in the text file
      - name: "Authenticate to pipelinesorg Org"
        run: sf org login sfdx-url --sfdx-url-file authFile.txt

      - name: 'Deploy delta packages to pipelinesorg'
        run: |
          sgd --to "main" --from "HEAD" --output .sgd
          sf project deploy start -d .sgd --target-org "dummypipelinetestingorg@abcd.com"

      - name: "Populate auth file with SFDX_URL secret of miltonOrg org"
        run: |
          echo ${{ secrets.SFDX_AUTH_URL2}} > ./authFile2.txt

      # Authenticate to org using the URL stored in the text file
      - name: "Authenticate to miltonOrg Org"
        run: sf org login sfdx-url --sfdx-url-file authFile2.txt

      - name: 'Deploy delta packages to miltonOrg'
        run: |
          sgd --to "main" --from "HEAD" --output .sgd
          sf project deploy start -d .sgd --target-org "klomax@abcd.com"
