name: Deploy project

on:
  pull_request:
    types: [closed]

jobs:
  merge-jobs:
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-slim
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Installing sfdx git delta"
        run: |
          echo y | sf plugins:install sfdx-git-delta@5.42.0
          sf plugins

      - name: "Populate auth file with SFDX_URL secret of pipelinesorg org"
        run: |
          echo ${{ secrets.SFDX_AUTH_URL}} > ./authFile.txt

      - name: "Authenticate to pipelinesorg Org"
        run: sf org login sfdx-url --sfdx-url-file authFile.txt
        
      - name: "Create delta packages for new, modified or deleted metadata"
        run: |
            sf sgd:source:delta --to HEAD --from HEAD~1 --output delta-package
            
      - name: 'Deploy delta packages to pipelinesorg'
        run: |
          sf project deploy start -d delta-package --target-org "dummypipelinetestingorg@abcd.com"

      - name: "Populate auth file with SFDX_URL secret of miltonOrg org"
        run: |
          echo ${{ secrets.SFDX_AUTH_URL2}} > ./authFile2.txt

      - name: "Authenticate to miltonOrg Org"
        run: sf org login sfdx-url --sfdx-url-file authFile2.txt

      - name: 'Deploy to Dev'
        run: |
          sf project deploy start -d force-app --target-org "klomax@abcd.com"
