name: Validate pull request in SIT

on:
  pull_request:
    branches:
      - SIT
    types: [opened, synchronize]
    paths:
      - 'force-app/**'

jobs:
  validate-deployment-qa:
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-slim
    steps:      
      - name: 'Checkout source code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: 'Authenticate using SFDX_AUTH_URL3'
        run: | 
          echo ${{ secrets.SFDX_AUTH_URL3 }} | sf org login sfdx-url -s -u

      - name: 'Validate'
        run: |
          sf project deploy validate -d force-app/ -l RunLocalTests -w 30          
